[metadata]
name = aioresponses
author = Pawel Nuckowski
author_email = p.nuckowski@gmail.com
summary = Mock out requests made by ClientSession from aiohttp package
description_file = README.rst
home_page = https://github.com/pnuckowski/aioresponses
python_requires = >=3.10
classifier =
  Development Status :: 4 - Beta
  Intended Audience :: Developers
  Operating System :: OS Independent
  Topic :: Internet :: WWW/HTTP
  Topic :: Software Development :: Testing
  Topic :: Software Development :: Testing :: Mocking
  License :: OSI Approved :: MIT License
  Natural Language :: English
  Programming Language :: Python :: 3
  Programming Language :: Python :: 3 :: Only
  Programming Language :: Python :: 3.10
  Programming Language :: Python :: 3.11
  Programming Language :: Python :: 3.12
  Programming Language :: Python :: 3.13
  Programming Language :: Python :: 3.14

[files]
packages =
 aioresponses


[flake8]
max-line-length = 120

[tool:pytest]
testpaths = tests
