name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  python-major-version: 3

concurrency:
  group: ci-${{ github.ref }}-${{ github.actor }}
  cancel-in-progress: true

jobs:
  build:
    env:
      PYTEST_ADDOPTS: "--cov --cov-report=xml"

    strategy:
      fail-fast: false
      matrix:
        include:
          - python-minor-version: 7
            aiohttp-version: aiohttp33
            os: ubuntu-latest
          - python-minor-version: 7
            aiohttp-version: aiohttp34
            os: ubuntu-latest
          - python-minor-version: 7
            aiohttp-version: aiohttp35
            os: ubuntu-latest
          - python-minor-version: 7
            aiohttp-version: aiohttp36
            os: ubuntu-latest
          - python-minor-version: 7
            aiohttp-version: aiohttp37
            os: ubuntu-latest
          - python-minor-version: 7
            aiohttp-version: aiohttp38
            os: ubuntu-latest

          - python-minor-version: 8
            aiohttp-version: aiohttp33
            os: ubuntu-latest
          - python-minor-version: 8
            aiohttp-version: aiohttp34
            os: ubuntu-latest
          - python-minor-version: 8
            aiohttp-version: aiohttp35
            os: ubuntu-latest
          - python-minor-version: 8
            aiohttp-version: aiohttp36
            os: ubuntu-latest
          - python-minor-version: 8
            aiohttp-version: aiohttp37
            os: ubuntu-latest
          - python-minor-version: 8
            aiohttp-version: aiohttp38
            os: ubuntu-latest

          - python-minor-version: 9
            aiohttp-version: aiohttp35
            os: ubuntu-latest
          - python-minor-version: 9
            aiohttp-version: aiohttp36
            os: ubuntu-latest
          - python-minor-version: 9
            aiohttp-version: aiohttp37
            os: ubuntu-latest
          - python-minor-version: 9
            aiohttp-version: aiohttp38
            os: ubuntu-latest

          - python-minor-version: 10
            aiohttp-version: aiohttp37
            os: ubuntu-latest
          - python-minor-version: 10
            aiohttp-version: aiohttp38
            os: ubuntu-latest

          - python-minor-version: 11
            aiohttp-version: aiohttp38
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ env.python-major-version }}.${{ matrix.python-minor-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.python-major-version }}.${{ matrix.python-minor-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - name: Run Tests
      run: |
        tox -e py${{ env.python-major-version }}${{ matrix.python-version }}-${{ matrix.aiohttp-version }}
    - uses: codecov/codecov-action@v2
      with:
        file: coverage.xml
